apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: go-sales-stream
  name: analytics-deployment
  labels:
    app: analytics
spec:
  replicas: 3
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
      - name: analytics
        image: analytics-service:v2
        ports:
        - containerPort: 9001