apiVersion: v1
kind: Service
metadata:
  namespace: go-sales-stream
  name: transaction-service
spec:
  selector:
    app: transaction
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000